
import React from 'react';
import { getTranslation } from '@/utils/translations';

interface ReadOnlyPaybackProps {
  businessCaseData: {
    resiAnnuali: number;
    resiMensili: number;
    carrelloMedio: number;
  };
  scenarioData: {
    rdvPercentage: number;
    upsellingPercentage: number;
  };
  monthlyTotal: number;
  language: string;
}

const ReadOnlyPayback = ({ businessCaseData, scenarioData, monthlyTotal, language }: ReadOnlyPaybackProps) => {
  // Calculate payback period using the SAME business logic as BusinessCase.tsx
  const annualReturns = businessCaseData.resiAnnuali > 0 ? businessCaseData.resiAnnuali : businessCaseData.resiMensili * 12;
  
  // Calculate RDV revenue (matching BusinessCase exactly)
  const rdvValue = annualReturns * 0.35 * businessCaseData.carrelloMedio;
  
  // Calculate upselling revenue (matching BusinessCase exactly)
  const upsellingResi = annualReturns * 0.0378;
  const upsellingAOV = businessCaseData.carrelloMedio * 1.3; // 30% increase
  const upsellingValue = upsellingResi * upsellingAOV;
  
  // Net revenue generated by REVER
  const fatturazioneGenerataRever = rdvValue + upsellingValue;
  
  // Total platform cost (annual)
  const annualPlatformCost = monthlyTotal * 12;
  
  // Calculate payback using the SAME formula as BusinessCase
  const paybackMonths = annualPlatformCost > 0 ? annualPlatformCost / (fatturazioneGenerataRever / 12) : 0;

  console.log('ReadOnlyPayback Debug:', {
    fatturazioneGenerataRever,
    monthlyTotal,
    annualPlatformCost,
    paybackMonths,
    showPayback: paybackMonths > 0 && paybackMonths < 120
  });

  // Show if payback exists and is meaningful (changed logic to be more visible)
  if (paybackMonths <= 0 || paybackMonths > 120) {
    return null;
  }

  return (
    <div className="p-4 rounded-xl border" style={{ backgroundColor: '#E9F9EC', borderColor: '#4CAF50' }}>
      <div className="flex items-center gap-2">
        <span className="text-gray-800 font-semibold">
          ⏳ {getTranslation(language, 'estimatedPayback')}: {paybackMonths.toFixed(1)} {getTranslation(language, 'monthsToRecoverInvestment')}
        </span>
      </div>
    </div>
  );
};

export default ReadOnlyPayback;
