// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwukchugdhapggvjkgnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53dWtjaHVnZGhhcGdndmprZ25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Nzc2MDEsImV4cCI6MjA2NDU1MzYwMX0.3Bm6bXboicZblMvxRCe2CIScYrDPD4-AltRdzukmpI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);